# Generated by Django 4.0.3 on 2022-04-12 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('segment', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('genre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('born', models.DateField()),
                ('favourite_number', models.IntegerField()),
                ('favourite_brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_brand', to='MVT.brand')),
                ('favourite_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='favourite_movie', to='MVT.movie')),
            ],
        ),
    ]
