# Generated by Django 4.0.3 on 2022-04-12 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='brand',
            new_name='favourite_brand',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='color',
            new_name='favourite_color',
        ),
    ]
